# -*- coding: utf-8 -*-
"""Generate _redirects, blocking every root file that is not a page.

Run:  python _build_redirects.py

WHY THIS EXISTS RATHER THAN A GLOB IN netlify.toml
Netlify redirect splats must be TRAILING. A pattern like "/*.md" -- with
characters after the asterisk -- is accepted by the config parser and
then silently never matches. That was verified against production: with
those rules deployed, BILT_STUDIO_HANDOFF.md, SEO.md, PLACEHOLDERS.md and
every generator script still returned 200, while the explicit rules
(/package.json, /hero.html, /db/*) correctly returned 404.

So the block list has to be explicit, one line per file. Enumerating it
by hand is how it goes stale the moment someone adds a file, hence this
script: it reads the directory and writes the list, and re-running it is
part of the build.

publish = "." is the underlying problem. The properly clean fix is a
publish directory containing only what is served, which is a larger
restructure; this closes the hole in the meantime.
"""
import io, os

ROOT = os.path.dirname(os.path.abspath(__file__))

# Everything a browser is allowed to fetch from the site root.
SERVE_FILES = {'index.html', '404.html', 'robots.txt', 'sitemap.xml', 'llms.txt',
               'favicon.ico', 'site.webmanifest', '_headers', '_redirects'}
SERVE_DIRS = {'assets', 'css', 'js', 'img', 'img-stock', 'kitchens', 'legal',
              'roomplanner'}

# Directories that must never be readable, whether or not they exist yet.
BLOCK_DIRS = ['netlify', 'db', 'docs', 'node_modules', '__pycache__', '.netlify',
              'scripts', 'drizzle']


def build():
    lines = [
        '# GENERATED by _build_redirects.py -- do not edit by hand.',
        '#',
        '# publish = "." serves this whole directory, so every file below would',
        '# otherwise be fetchable over HTTP. Netlify splats must be trailing, so',
        '# "/*.md" does not work and each file needs its own line.',
        '#',
        '# Format: <from> <to> <status>   -- 404! forces the status.',
        '',
    ]

    blocked = []
    for name in sorted(os.listdir(ROOT)):
        path = os.path.join(ROOT, name)
        if os.path.isdir(path):
            continue
        if name in SERVE_FILES or name.startswith('.'):
            continue
        blocked.append(name)

    for name in blocked:
        lines.append('/%s /404.html 404!' % name)

    lines.append('')
    lines.append('# Directories with nothing public in them.')
    for d in BLOCK_DIRS:
        lines.append('/%s/* /404.html 404!' % d)

    lines.append('')
    io.open(os.path.join(ROOT, '_redirects'), 'w', encoding='utf-8',
            newline='\n').write('\n'.join(lines))
    return blocked


if __name__ == '__main__':
    b = build()
    print('_redirects written: %d root files blocked, %d directories' % (len(b), len(BLOCK_DIRS)))
    for n in b:
        print('   /%s' % n)
