/* National coverage dataset: 8 states and territories, 54 regions, 284 towns.
 *
 * Every field is checkable geography or a characterisation of the housing
 * stock. There are deliberately no distances in kilometres, populations,
 * freight prices or lead times per town - those would have to be invented,
 * and the quote states the real ones for the real job.
 *
 * Consumed by _pages.js: statePage(), regionPage(), townPage().
 */
const STATES = {
  'QLD': { slug: 'queensland', name: 'Queensland', body: 'QBCC', url: 'https://www.qbcc.qld.gov.au/', skip: false },
  'NSW': { slug: 'nsw', name: 'New South Wales', body: 'NSW Fair Trading', url: 'https://www.fairtrading.nsw.gov.au/', skip: true },
  'VIC': { slug: 'victoria', name: 'Victoria', body: 'the Victorian Building Authority', url: 'https://www.vba.vic.gov.au/', skip: true },
  'SA': { slug: 'south-australia', name: 'South Australia', body: 'SA Consumer and Business Services', url: 'https://www.cbs.sa.gov.au/', skip: false },
  'WA': { slug: 'western-australia', name: 'Western Australia', body: 'the WA Building and Energy division', url: 'https://www.commerce.wa.gov.au/building-and-energy', skip: false },
  'TAS': { slug: 'tasmania', name: 'Tasmania', body: 'Consumer, Building and Occupational Services', url: 'https://cbos.tas.gov.au/', skip: false },
  'NT': { slug: 'northern-territory', name: 'the Northern Territory', body: 'NT Building Practitioners Board', url: 'https://nt.gov.au/property/building-and-development', skip: false },
  'ACT': { slug: 'act', name: 'the ACT', body: 'Access Canberra', url: 'https://www.accesscanberra.act.gov.au/', skip: false },
};

/* One paragraph per climate zone. This is the honest reason the board and
   edging specification differs in argument from region to region even though
   the product does not. */
const CLIMATE = {
  'tropical': ['Humidity is the design constraint here, not heat. Through the wet season a standard-core carcass takes on moisture at the cut edges and swells, and once a panel has swollen the door never sits square again. Everything we ship is 18mm moisture-resistant board with laser-bonded edging — no glue line for water to track along — because in this climate that is not an upgrade, it is the minimum that survives.', 'moisture-resistant board and laser-bonded edging'],
  'subtropical': ['Summers here are humid enough that the cheap end of flat pack fails at the sink and dishwasher first, usually inside five years. Moisture-resistant board and laser-bonded edging are standard on every cabinet we cut, which is the difference between a kitchen that still closes properly at year ten and one that does not.', 'moisture-resistant board and laser-bonded edging'],
  'temperate': ['The seasonal swing here moves timber and board more than a steady climate does, and the joint that gives first is almost always the edge. Laser-bonded edging is fused to the panel rather than glued to it, so there is no seam to lift as the material expands and contracts through the year.', 'laser-bonded edging that will not lift'],
  'arid': ['Dry heat, dust and hard water are the local test. Dry heat shrinks poorly-made joints and dust finds its way into cheap runners until they grate. Blum runners and hinges are sealed, rated for a hundred thousand cycles and carry a lifetime mechanical warranty, which is why we fit nothing else.', 'Blum hardware rated for the dust and the dry'],
  'cool': ['Cold, damp winters in older uninsulated housing produce condensation, and condensation sits on the underside of a benchtop and in the back of a sink cabinet where nobody looks. Moisture-resistant board handles that; standard board swells quietly for a year and then lets go.', 'moisture-resistant board for damp winters'],
};

/* One paragraph per town type - what the local housing stock does to a
   kitchen. */
const KIND = {
  'coastal': 'Salt air is relentless on hardware. It gets into unbranded runners and hinges and they stiffen, then sag, and the doors stop lining up. Every cabinet we cut runs Blum soft-close hinges and full-extension runners as standard, which is the part of a coastal kitchen worth spending on.',
  'mining': 'A lot of housing here is worked hard and turned over fast — tenants, shift workers, company accommodation. That is a specification argument, not a design one: 18mm carcasses that hold a screw, drawers that survive being slammed, and doors that can be readjusted rather than replaced.',
  'farming': 'The nearest cabinetmaker is not close, and that changes what matters. A complete, labelled delivery with every panel pre-drilled and every hardware bag matched to its cabinet means the job does not stall waiting on one missing part from three hours away.',
  'commuter': 'Access is usually the deciding factor here — townhouses, units, narrow hallways, stairs. A flat carton goes where an assembled cabinet cannot, and it is often the only way to get a full kitchen into the room without taking a window out.',
  'lifestyle': 'Short-stay and weekender properties get judged on a photograph and then punished by turnover. That combination wants a kitchen that looks like a magazine and behaves like a rental: stone or stone-look benchtops over carcasses and hardware specified to be used hard.',
  'regional': 'As the service town for the district, the housing here runs from century-old cottages to new estate builds, and almost none of it suits a catalogue cabinet width. Every run we cut is drawn to the wall it is going on, so filler panels are a choice rather than a necessity.',
  'alpine': 'Kitchens here sit cold and closed out of season, then get used hard for a few intense weeks. Temperature cycling like that is what lifts glued edging and loosens cheap hinges, and it is the case for the specification we ship as standard.',
};

const REGIONS = [
  { slug: 'far-north-queensland', name: 'Far North Queensland', state: 'QLD', climate: 'tropical', route: 'north along the Bruce Highway', context: 'Wet-season humidity here is the hardest test a kitchen carcass gets anywhere in Australia, and it is the reason we do not sell 16mm standard board at all.', towns: [['port-douglas', 'Port Douglas', 'coastal'], ['mareeba', 'Mareeba', 'farming'], ['atherton', 'Atherton', 'farming'], ['innisfail', 'Innisfail', 'regional'], ['tully', 'Tully', 'farming'], ['mossman', 'Mossman', 'farming'], ['cooktown', 'Cooktown', 'coastal'], ['weipa', 'Weipa', 'mining'], ['gordonvale', 'Gordonvale', 'regional']] },
  { slug: 'north-queensland', name: 'North Queensland', state: 'QLD', climate: 'tropical', route: 'north along the Bruce Highway', context: 'Dry tropics rather than wet: hot, salty air near the coast and hard water inland, both of which show up on hardware long before they show up on doors.', towns: [['ayr', 'Ayr', 'farming'], ['ingham', 'Ingham', 'farming'], ['charters-towers', 'Charters Towers', 'mining'], ['bowen', 'Bowen', 'coastal'], ['home-hill', 'Home Hill', 'farming'], ['magnetic-island', 'Magnetic Island', 'coastal']] },
  { slug: 'mackay-whitsunday', name: 'Mackay and the Whitsundays', state: 'QLD', climate: 'tropical', route: 'north along the Bruce Highway', context: 'Half the kitchens quoted here are holiday lets, and a let kitchen is judged on how it photographs and how it survives a turnover every three days.', towns: [['airlie-beach', 'Airlie Beach', 'coastal'], ['proserpine', 'Proserpine', 'farming'], ['sarina', 'Sarina', 'farming'], ['cannonvale', 'Cannonvale', 'coastal'], ['bowen-basin', 'the Bowen Basin', 'mining']] },
  { slug: 'central-queensland', name: 'Central Queensland', state: 'QLD', climate: 'subtropical', route: 'from our own door', context: 'This is home. Everything else on the site ships; here we also measure, deliver and install with our own team.', towns: [['moura', 'Moura', 'mining'], ['clermont', 'Clermont', 'mining'], ['dysart', 'Dysart', 'mining'], ['middlemount', 'Middlemount', 'mining'], ['capella', 'Capella', 'farming'], ['springsure', 'Springsure', 'farming'], ['mount-morgan', 'Mount Morgan', 'regional'], ['tannum-sands', 'Tannum Sands', 'coastal'], ['calliope', 'Calliope', 'regional'], ['emu-park', 'Emu Park', 'coastal']] },
  { slug: 'wide-bay-burnett', name: 'Wide Bay and Burnett', state: 'QLD', climate: 'subtropical', route: 'south along the Bruce Highway', context: 'A lot of downsizers and a lot of second dwellings on big blocks, which is why the kitchenette gets asked about here more than anywhere else.', towns: [['maryborough', 'Maryborough', 'regional'], ['gympie', 'Gympie', 'regional'], ['kingaroy', 'Kingaroy', 'farming'], ['childers', 'Childers', 'farming'], ['gayndah', 'Gayndah', 'farming'], ['hervey-bay-qld', 'Hervey Bay', 'coastal'], ['tin-can-bay', 'Tin Can Bay', 'coastal']] },
  { slug: 'sunshine-coast', name: 'the Sunshine Coast', state: 'QLD', climate: 'subtropical', route: 'south along the Bruce Highway', context: 'Coastal humidity plus a renovation market that expects a stone benchtop as a starting point rather than an upgrade.', towns: [['maroochydore', 'Maroochydore', 'coastal'], ['noosa', 'Noosa', 'lifestyle'], ['nambour', 'Nambour', 'regional'], ['buderim', 'Buderim', 'lifestyle'], ['coolum-beach', 'Coolum Beach', 'coastal'], ['caloundra-qld', 'Caloundra', 'coastal'], ['gympie-region', 'the Gympie region', 'regional']] },
  { slug: 'greater-brisbane', name: 'Greater Brisbane', state: 'QLD', climate: 'subtropical', route: 'south along the Bruce Highway', context: 'Freight lands daily, which makes Brisbane the cheapest capital for us to reach and the easiest place to compare our quote against a local one.', towns: [['ipswich', 'Ipswich', 'commuter'], ['logan', 'Logan', 'commuter'], ['redlands', 'the Redlands', 'commuter'], ['caboolture', 'Caboolture', 'commuter'], ['redcliffe', 'Redcliffe', 'coastal'], ['springfield', 'Springfield', 'commuter'], ['north-lakes', 'North Lakes', 'commuter']] },
  { slug: 'gold-coast-hinterland', name: 'the Gold Coast and hinterland', state: 'QLD', climate: 'subtropical', route: 'south along the Bruce Highway', context: 'Short-stay and dual-occupancy work dominates, and both are decided on how fast the kitchen can be in and earning.', towns: [['southport', 'Southport', 'commuter'], ['robina', 'Robina', 'commuter'], ['coolangatta', 'Coolangatta', 'coastal'], ['nerang', 'Nerang', 'commuter'], ['burleigh-heads', 'Burleigh Heads', 'coastal'], ['tamborine-mountain', 'Tamborine Mountain', 'lifestyle']] },
  { slug: 'darling-downs', name: 'the Darling Downs', state: 'QLD', climate: 'temperate', route: 'south along the Warrego and Gore highways', context: 'Cold winter mornings and hot dry summers move timber more than the coast does, which is a case for laser-bonded edging rather than glued.', towns: [['warwick', 'Warwick', 'farming'], ['dalby', 'Dalby', 'farming'], ['stanthorpe', 'Stanthorpe', 'farming'], ['chinchilla', 'Chinchilla', 'farming'], ['roma', 'Roma', 'mining'], ['goondiwindi', 'Goondiwindi', 'farming'], ['miles', 'Miles', 'farming'], ['oakey', 'Oakey', 'farming']] },
  { slug: 'outback-queensland', name: 'Outback Queensland', state: 'QLD', climate: 'arid', route: 'west via the Capricorn Highway', context: 'Freight is the whole conversation out here, and flat cartons are the only version of this that makes financial sense.', towns: [['mount-isa', 'Mount Isa', 'mining'], ['longreach', 'Longreach', 'farming'], ['charleville', 'Charleville', 'farming'], ['barcaldine', 'Barcaldine', 'farming'], ['cloncurry', 'Cloncurry', 'mining'], ['winton', 'Winton', 'farming']] },
  { slug: 'greater-sydney', name: 'Greater Sydney', state: 'NSW', climate: 'temperate', route: 'south along the Pacific and New England highways', context: 'Most enquiries here are apartments and semis where a built cabinet will not fit through the door, which is exactly what flat pack solves.', towns: [['penrith', 'Penrith', 'commuter'], ['parramatta', 'Parramatta', 'commuter'], ['campbelltown', 'Campbelltown', 'commuter'], ['blacktown', 'Blacktown', 'commuter'], ['liverpool', 'Liverpool', 'commuter'], ['hornsby', 'Hornsby', 'commuter'], ['sutherland-shire', 'the Sutherland Shire', 'commuter'], ['northern-beaches', 'the Northern Beaches', 'coastal']] },
  { slug: 'central-coast-nsw', name: 'the NSW Central Coast', state: 'NSW', climate: 'temperate', route: 'south along the Pacific Highway', context: 'Salt air and a lot of 1970s brick houses being opened up, which usually means the run gets longer and the island arrives.', towns: [['gosford', 'Gosford', 'commuter'], ['wyong', 'Wyong', 'commuter'], ['terrigal', 'Terrigal', 'coastal'], ['the-entrance', 'The Entrance', 'coastal'], ['woy-woy', 'Woy Woy', 'commuter']] },
  { slug: 'hunter-valley', name: 'the Hunter Valley', state: 'NSW', climate: 'temperate', route: 'south along the Pacific Highway', context: 'Mining money, wine-country short stays and a strong owner-builder culture, so we quote flat pack and assembled about equally here.', towns: [['maitland', 'Maitland', 'regional'], ['cessnock', 'Cessnock', 'lifestyle'], ['singleton', 'Singleton', 'mining'], ['muswellbrook', 'Muswellbrook', 'mining'], ['port-stephens', 'Port Stephens', 'coastal'], ['nelson-bay', 'Nelson Bay', 'coastal'], ['raymond-terrace', 'Raymond Terrace', 'regional'], ['scone', 'Scone', 'farming']] },
  { slug: 'illawarra', name: 'the Illawarra', state: 'NSW', climate: 'temperate', route: 'south along the Hume corridor', context: 'Escarpment blocks and split-level houses, where getting an assembled cabinet down a flight of external stairs is the argument for cartons.', towns: [['shellharbour', 'Shellharbour', 'coastal'], ['kiama', 'Kiama', 'coastal'], ['nowra', 'Nowra', 'regional'], ['ulladulla', 'Ulladulla', 'coastal'], ['dapto', 'Dapto', 'commuter']] },
  { slug: 'northern-rivers', name: 'the Northern Rivers', state: 'NSW', climate: 'subtropical', route: 'south along the Pacific Highway', context: 'Subtropical humidity and a flood history that has made people specific about board grade in a way most regions are not.', towns: [['lismore', 'Lismore', 'regional'], ['ballina', 'Ballina', 'coastal'], ['byron-bay', 'Byron Bay', 'lifestyle'], ['tweed-heads', 'Tweed Heads', 'coastal'], ['casino', 'Casino', 'farming'], ['grafton', 'Grafton', 'regional'], ['yamba', 'Yamba', 'coastal'], ['murwillumbah', 'Murwillumbah', 'regional']] },
  { slug: 'mid-north-coast', name: 'the Mid North Coast', state: 'NSW', climate: 'subtropical', route: 'south along the Pacific Highway', context: 'Retirement and holiday-let building, which means kitchenettes and compact kitchens outnumber full renovations.', towns: [['coffs-harbour', 'Coffs Harbour', 'coastal'], ['port-macquarie', 'Port Macquarie', 'coastal'], ['taree', 'Taree', 'regional'], ['kempsey', 'Kempsey', 'regional'], ['forster', 'Forster', 'coastal'], ['nambucca-heads', 'Nambucca Heads', 'coastal']] },
  { slug: 'new-england', name: 'New England and the North West', state: 'NSW', climate: 'temperate', route: 'south along the New England Highway', context: 'Genuinely cold winters on the tablelands, and the temperature swing is why we specify the edging we do.', towns: [['tamworth', 'Tamworth', 'regional'], ['armidale', 'Armidale', 'regional'], ['inverell', 'Inverell', 'farming'], ['glen-innes', 'Glen Innes', 'farming'], ['gunnedah', 'Gunnedah', 'farming'], ['moree', 'Moree', 'farming'], ['narrabri', 'Narrabri', 'farming']] },
  { slug: 'central-west-nsw', name: 'the Central West', state: 'NSW', climate: 'temperate', route: 'south along the Newell Highway', context: 'Big country blocks with second dwellings for family, and a steady run of Federation-era houses being brought up to date.', towns: [['orange', 'Orange', 'lifestyle'], ['bathurst', 'Bathurst', 'regional'], ['dubbo', 'Dubbo', 'regional'], ['mudgee', 'Mudgee', 'lifestyle'], ['parkes', 'Parkes', 'farming'], ['forbes', 'Forbes', 'farming'], ['cowra', 'Cowra', 'farming'], ['lithgow', 'Lithgow', 'regional']] },
  { slug: 'riverina', name: 'the Riverina', state: 'NSW', climate: 'temperate', route: 'south along the Newell Highway', context: 'Irrigation-town wealth and a lot of farm housing, where a kitchen is expected to take twenty years of hard use.', towns: [['wagga-wagga', 'Wagga Wagga', 'regional'], ['griffith', 'Griffith', 'farming'], ['albury', 'Albury', 'regional'], ['leeton', 'Leeton', 'farming'], ['narrandera', 'Narrandera', 'farming'], ['tumut', 'Tumut', 'farming'], ['deniliquin', 'Deniliquin', 'farming']] },
  { slug: 'far-west-nsw', name: 'Far West NSW', state: 'NSW', climate: 'arid', route: 'west via the Barrier Highway', context: 'Extreme dry heat and long freight runs, so cartons and a fixed freight line matter more here than anywhere.', towns: [['broken-hill', 'Broken Hill', 'mining'], ['cobar', 'Cobar', 'mining'], ['bourke', 'Bourke', 'farming']] },
  { slug: 'south-coast-nsw', name: 'the NSW South Coast', state: 'NSW', climate: 'temperate', route: 'south along the Hume corridor', context: 'Holiday houses that sit empty half the year, which is hard on hardware and unforgiving of cheap runners.', towns: [['batemans-bay', 'Batemans Bay', 'coastal'], ['merimbula', 'Merimbula', 'coastal'], ['bega', 'Bega', 'farming'], ['eden', 'Eden', 'coastal'], ['narooma', 'Narooma', 'coastal'], ['moruya', 'Moruya', 'regional']] },
  { slug: 'southern-tablelands', name: 'the Southern Tablelands and Snowy', state: 'NSW', climate: 'cool', route: 'south along the Hume Highway', context: 'Alpine and near-alpine housing, where kitchens are used hard in season and left cold and empty out of it.', towns: [['goulburn', 'Goulburn', 'regional'], ['queanbeyan', 'Queanbeyan', 'commuter'], ['yass', 'Yass', 'farming'], ['cooma', 'Cooma', 'alpine'], ['jindabyne', 'Jindabyne', 'alpine'], ['bowral', 'Bowral', 'lifestyle']] },
  { slug: 'greater-melbourne', name: 'Greater Melbourne', state: 'VIC', climate: 'temperate', route: 'south along the Newell and Hume highways', context: 'The most competitive flat pack market in the country, and the one where the board and hardware specification is worth reading twice.', towns: [['werribee', 'Werribee', 'commuter'], ['frankston', 'Frankston', 'commuter'], ['dandenong', 'Dandenong', 'commuter'], ['ringwood', 'Ringwood', 'commuter'], ['craigieburn', 'Craigieburn', 'commuter'], ['pakenham', 'Pakenham', 'commuter'], ['sunbury', 'Sunbury', 'commuter'], ['melton', 'Melton', 'commuter']] },
  { slug: 'mornington-peninsula', name: 'the Mornington Peninsula', state: 'VIC', climate: 'temperate', route: 'south along the Hume Highway', context: 'Weekenders and permanent downsizers in the same street, wanting the same kitchen to do both jobs.', towns: [['mornington', 'Mornington', 'lifestyle'], ['rosebud', 'Rosebud', 'coastal'], ['hastings', 'Hastings', 'regional'], ['sorrento', 'Sorrento', 'lifestyle']] },
  { slug: 'bellarine-surf-coast', name: 'the Bellarine and Surf Coast', state: 'VIC', climate: 'temperate', route: 'south along the Hume Highway', context: 'Salt-exposed coastal housing with a short, intense summer season for short-stay turnover.', towns: [['torquay', 'Torquay', 'coastal'], ['ocean-grove', 'Ocean Grove', 'coastal'], ['lorne', 'Lorne', 'lifestyle'], ['anglesea', 'Anglesea', 'coastal'], ['barwon-heads', 'Barwon Heads', 'coastal']] },
  { slug: 'ballarat-goldfields', name: 'Ballarat and the Goldfields', state: 'VIC', climate: 'cool', route: 'south along the Hume Highway', context: 'Victorian-era cottages with small, awkward kitchens where a cut-to-size run beats a catalogue every time.', towns: [['ballarat', 'Ballarat', 'regional'], ['bendigo', 'Bendigo', 'regional'], ['castlemaine', 'Castlemaine', 'lifestyle'], ['maryborough-vic', 'Maryborough', 'regional'], ['daylesford', 'Daylesford', 'lifestyle'], ['kyneton', 'Kyneton', 'lifestyle']] },
  { slug: 'gippsland', name: 'Gippsland', state: 'VIC', climate: 'temperate', route: 'south along the Hume Highway', context: 'Farm housing and a long coastline, with a strong owner-builder tradition on both.', towns: [['traralgon', 'Traralgon', 'regional'], ['sale', 'Sale', 'regional'], ['bairnsdale', 'Bairnsdale', 'regional'], ['warragul', 'Warragul', 'farming'], ['leongatha', 'Leongatha', 'farming'], ['wonthaggi', 'Wonthaggi', 'regional'], ['lakes-entrance', 'Lakes Entrance', 'coastal'], ['phillip-island', 'Phillip Island', 'coastal']] },
  { slug: 'goulburn-valley', name: 'the Goulburn Valley', state: 'VIC', climate: 'temperate', route: 'south along the Newell Highway', context: 'Orchard and dairy country with big family houses and a practical view of what a kitchen needs to be.', towns: [['shepparton', 'Shepparton', 'farming'], ['echuca', 'Echuca', 'regional'], ['benalla', 'Benalla', 'regional'], ['wangaratta', 'Wangaratta', 'regional'], ['seymour', 'Seymour', 'regional']] },
  { slug: 'north-east-victoria', name: 'North East Victoria', state: 'VIC', climate: 'cool', route: 'south along the Hume Highway', context: 'Alpine and foothill housing where kitchens sit unheated through winter and are used hard in the ski and summer seasons.', towns: [['wodonga', 'Wodonga', 'regional'], ['bright', 'Bright', 'alpine'], ['myrtleford', 'Myrtleford', 'farming'], ['beechworth', 'Beechworth', 'lifestyle'], ['mansfield', 'Mansfield', 'alpine']] },
  { slug: 'western-victoria', name: 'Western Victoria', state: 'VIC', climate: 'temperate', route: 'south along the Hume Highway', context: 'Wind-exposed coast on one side and dry cropping country on the other, in the same freight run.', towns: [['warrnambool', 'Warrnambool', 'coastal'], ['hamilton', 'Hamilton', 'farming'], ['portland', 'Portland', 'coastal'], ['horsham', 'Horsham', 'farming'], ['ararat', 'Ararat', 'farming'], ['colac', 'Colac', 'farming']] },
  { slug: 'mallee', name: 'the Mallee', state: 'VIC', climate: 'arid', route: 'south along the Newell Highway', context: 'Dry heat, hard water and long distances between trades, which puts a premium on getting the drawings right first time.', towns: [['mildura', 'Mildura', 'farming'], ['swan-hill', 'Swan Hill', 'farming'], ['ouyen', 'Ouyen', 'farming']] },
  { slug: 'greater-adelaide', name: 'Greater Adelaide', state: 'SA', climate: 'temperate', route: 'west via the Barrier and Sturt highways', context: 'A lot of 1960s and 70s houses on generous blocks, which is why second dwellings and garage conversions come up so often here.', towns: [['gawler', 'Gawler', 'commuter'], ['mount-barker-sa', 'Mount Barker', 'commuter'], ['victor-harbor', 'Victor Harbor', 'coastal'], ['aldinga', 'Aldinga', 'commuter'], ['elizabeth', 'Elizabeth', 'commuter']] },
  { slug: 'barossa-mid-north', name: 'the Barossa and Mid North', state: 'SA', climate: 'temperate', route: 'west via the Sturt Highway', context: 'Cellar-door accommodation and farm housing, both of which get judged on how the kitchen photographs.', towns: [['nuriootpa', 'Nuriootpa', 'lifestyle'], ['tanunda', 'Tanunda', 'lifestyle'], ['clare', 'Clare', 'lifestyle'], ['kapunda', 'Kapunda', 'farming'], ['port-pirie', 'Port Pirie', 'regional']] },
  { slug: 'fleurieu-kangaroo-island', name: 'the Fleurieu and Kangaroo Island', state: 'SA', climate: 'temperate', route: 'west via the Sturt Highway', context: 'Island and coastal freight adds a leg, which is exactly when flat cartons stop being a preference and start being the answer.', towns: [['goolwa', 'Goolwa', 'coastal'], ['kingscote', 'Kingscote', 'coastal'], ['normanville', 'Normanville', 'coastal']] },
  { slug: 'yorke-eyre-peninsula', name: 'the Yorke and Eyre Peninsulas', state: 'SA', climate: 'temperate', route: 'west via the Eyre Highway', context: 'Long coastlines, salt air and towns where the nearest cabinetmaker is two hours away.', towns: [['port-lincoln', 'Port Lincoln', 'coastal'], ['whyalla', 'Whyalla', 'mining'], ['port-augusta', 'Port Augusta', 'regional'], ['kadina', 'Kadina', 'farming'], ['ceduna', 'Ceduna', 'coastal']] },
  { slug: 'riverland', name: 'the Riverland', state: 'SA', climate: 'arid', route: 'west via the Sturt Highway', context: 'Irrigation country: hot, dry, hard water, and a lot of housing built for workers rather than for looking at.', towns: [['berri', 'Berri', 'farming'], ['renmark', 'Renmark', 'farming'], ['loxton', 'Loxton', 'farming'], ['waikerie', 'Waikerie', 'farming']] },
  { slug: 'limestone-coast', name: 'the Limestone Coast', state: 'SA', climate: 'temperate', route: 'west via the Western and Princes highways', context: 'Cool, wet winters and a strong renovation market in the older timber housing stock.', towns: [['mount-gambier', 'Mount Gambier', 'regional'], ['naracoorte', 'Naracoorte', 'farming'], ['millicent', 'Millicent', 'regional']] },
  { slug: 'outback-sa', name: 'Outback South Australia', state: 'SA', climate: 'arid', route: 'west via the Stuart Highway', context: 'Remote freight and extreme heat, where an underground or heavily insulated house still needs a kitchen that behaves.', towns: [['coober-pedy', 'Coober Pedy', 'mining'], ['roxby-downs', 'Roxby Downs', 'mining']] },
  { slug: 'greater-perth', name: 'Greater Perth', state: 'WA', climate: 'temperate', route: 'west across the Nullarbor', context: 'The longest freight run we do, and the one where flat pack versus assembled is decided almost entirely by the freight line.', towns: [['joondalup', 'Joondalup', 'commuter'], ['rockingham', 'Rockingham', 'commuter'], ['mandurah', 'Mandurah', 'coastal'], ['armadale', 'Armadale', 'commuter'], ['ellenbrook', 'Ellenbrook', 'commuter'], ['fremantle', 'Fremantle', 'lifestyle']] },
  { slug: 'south-west-wa', name: 'the South West', state: 'WA', climate: 'temperate', route: 'west across the Nullarbor', context: 'Wine country and surf coast, with a short intense holiday season and a long quiet one.', towns: [['bunbury', 'Bunbury', 'regional'], ['busselton', 'Busselton', 'coastal'], ['margaret-river', 'Margaret River', 'lifestyle'], ['dunsborough', 'Dunsborough', 'coastal'], ['collie', 'Collie', 'mining'], ['manjimup', 'Manjimup', 'farming']] },
  { slug: 'great-southern-wa', name: 'the Great Southern', state: 'WA', climate: 'temperate', route: 'west across the Nullarbor', context: 'Cold, wet and wind-driven weather, which is hard on any cabinet that was built to a price.', towns: [['albany', 'Albany', 'coastal'], ['denmark', 'Denmark', 'lifestyle'], ['katanning', 'Katanning', 'farming'], ['mount-barker-wa', 'Mount Barker', 'farming']] },
  { slug: 'wheatbelt-wa', name: 'the Wheatbelt', state: 'WA', climate: 'arid', route: 'west across the Nullarbor', context: 'Farm housing a long way from any supplier, where a complete, labelled delivery matters more than a showroom.', towns: [['northam', 'Northam', 'farming'], ['narrogin', 'Narrogin', 'farming'], ['merredin', 'Merredin', 'farming'], ['york-wa', 'York', 'farming']] },
  { slug: 'mid-west-gascoyne', name: 'the Mid West and Gascoyne', state: 'WA', climate: 'arid', route: 'west across the Nullarbor', context: 'Coastal heat and cyclone-rated housing, with freight that rewards packing flat.', towns: [['geraldton', 'Geraldton', 'coastal'], ['carnarvon', 'Carnarvon', 'farming'], ['exmouth', 'Exmouth', 'coastal']] },
  { slug: 'pilbara', name: 'the Pilbara', state: 'WA', climate: 'tropical', route: 'west across the Nullarbor', context: 'Company housing and FIFO accommodation built to be replaced on a cycle, and private housing that has to survive cyclone season.', towns: [['karratha', 'Karratha', 'mining'], ['port-hedland', 'Port Hedland', 'mining'], ['newman', 'Newman', 'mining'], ['tom-price', 'Tom Price', 'mining']] },
  { slug: 'kimberley', name: 'the Kimberley', state: 'WA', climate: 'tropical', route: 'west across the Nullarbor', context: 'Wet-season humidity as hard as Far North Queensland, with freight distances that make a carton the only sensible format.', towns: [['broome', 'Broome', 'coastal'], ['kununurra', 'Kununurra', 'farming'], ['derby', 'Derby', 'regional']] },
  { slug: 'goldfields-esperance', name: 'the Goldfields and Esperance', state: 'WA', climate: 'arid', route: 'west across the Nullarbor', context: 'Mining housing inland and salt air on the coast, in one freight region.', towns: [['kalgoorlie', 'Kalgoorlie', 'mining'], ['esperance', 'Esperance', 'coastal'], ['boulder', 'Boulder', 'mining']] },
  { slug: 'hobart-south-tas', name: 'Hobart and the South', state: 'TAS', climate: 'cool', route: 'south then by sea across Bass Strait', context: 'Cold, damp winters in a lot of uninsulated older housing, which is where cheap board fails first.', towns: [['kingston-tas', 'Kingston', 'commuter'], ['new-norfolk', 'New Norfolk', 'regional'], ['huonville', 'Huonville', 'farming'], ['sorell', 'Sorell', 'commuter']] },
  { slug: 'launceston-north-tas', name: 'Launceston and the North', state: 'TAS', climate: 'cool', route: 'south then by sea across Bass Strait', context: 'Georgian and Federation housing with small original kitchens that almost never suit a catalogue cabinet width.', towns: [['launceston', 'Launceston', 'regional'], ['george-town', 'George Town', 'regional'], ['scottsdale', 'Scottsdale', 'farming'], ['deloraine', 'Deloraine', 'farming']] },
  { slug: 'north-west-tas', name: 'the North West Coast', state: 'TAS', climate: 'cool', route: 'south then by sea across Bass Strait', context: 'The Bass Strait crossing is part of every quote here, and it is quoted as its own line like any other freight leg.', towns: [['devonport', 'Devonport', 'regional'], ['burnie', 'Burnie', 'regional'], ['ulverstone', 'Ulverstone', 'coastal'], ['wynyard', 'Wynyard', 'coastal'], ['smithton', 'Smithton', 'farming']] },
  { slug: 'east-coast-tas', name: 'the Tasmanian East Coast', state: 'TAS', climate: 'cool', route: 'south then by sea across Bass Strait', context: 'Holiday housing that sits cold and closed for months, then gets used hard for six weeks.', towns: [['st-helens', 'St Helens', 'coastal'], ['bicheno', 'Bicheno', 'coastal'], ['swansea-tas', 'Swansea', 'coastal']] },
  { slug: 'darwin-top-end', name: 'Darwin and the Top End', state: 'NT', climate: 'tropical', route: 'north-west via the Barkly and Stuart highways', context: 'Build-up humidity is relentless, and it is the single strongest argument on this whole site for moisture-resistant board.', towns: [['palmerston', 'Palmerston', 'commuter'], ['humpty-doo', 'Humpty Doo', 'lifestyle'], ['howard-springs', 'Howard Springs', 'lifestyle']] },
  { slug: 'katherine-big-rivers', name: 'Katherine and Big Rivers', state: 'NT', climate: 'tropical', route: 'north-west via the Barkly and Stuart highways', context: 'Long freight legs and a wet season that closes roads, so delivery timing is planned around the calendar rather than the quote.', towns: [['katherine', 'Katherine', 'regional']] },
  { slug: 'central-australia', name: 'Central Australia', state: 'NT', climate: 'arid', route: 'north-west via the Barkly and Stuart highways', context: 'Extreme dry heat and dust, and a long way from any cabinetmaker, which is the case for a complete labelled delivery.', towns: [['alice-springs', 'Alice Springs', 'regional'], ['tennant-creek', 'Tennant Creek', 'mining']] },
  { slug: 'act-region', name: 'the ACT and region', state: 'ACT', climate: 'cool', route: 'south along the Newell and Hume highways', context: 'Genuinely cold winters, a lot of townhouses with tight access, and a rental market that turns over hard.', towns: [['gungahlin', 'Gungahlin', 'commuter'], ['tuggeranong', 'Tuggeranong', 'commuter'], ['belconnen', 'Belconnen', 'commuter'], ['woden', 'Woden', 'commuter']] },
];

module.exports = { STATES, CLIMATE, KIND, REGIONS };
